In [2]:
import torch

torch.rand(1), list(range(10))

(tensor([0.1417]), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = torch.rand((2,6))
print(a)
torch.argmax(a, dim=1)

tensor([[0.0857, 0.8364, 0.4044, 0.1227, 0.2062, 0.6550],
        [0.6133, 0.4087, 0.0482, 0.1303, 0.7554, 0.2742]])


tensor([1, 4])