In [1]:
import torch

torch.rand(1), list(range(10))

(tensor([0.1325]), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = torch.rand((2,6))
print(a)
torch.argmax(a, dim=1)

tensor([[0.0857, 0.8364, 0.4044, 0.1227, 0.2062, 0.6550],
        [0.6133, 0.4087, 0.0482, 0.1303, 0.7554, 0.2742]])


tensor([1, 4])

In [5]:
torch.randint(0, 4, (1,)).size()

torch.Size([1])

In [8]:
import numpy as np
import time

a = np.array([1,2,3,4,5,6])

start = time.time()
b = torch.tensor(a, dtype=torch.float, device="cuda")
print(b, b.dtype, b.size())
end = time.time()
print(f"running time : {(end - start) / 60:.3f} min")

start = time.time()
c = torch.from_numpy(a).float().to("cuda")
print(c, c.dtype, c.size())
end = time.time()
print(f"running time : {(end - start) / 60:.7f} min")

tensor([1., 2., 3., 4., 5., 6.], device='cuda:0') torch.float32 torch.Size([6])
running time : 0.014 min
tensor([1., 2., 3., 4., 5., 6.], device='cuda:0') torch.float32 torch.Size([6])
running time : 0.0000524 min


In [6]:
import torch
import numpy as np

a = torch.randint(0, 10, (6, 4))
b = torch.from_numpy(np.random.randint(low=4, size=(6,)))
print(a)
print(b)
X = a.gather(dim=1, index=b.long().unsqueeze(dim=1))#.squeeze()
X, torch.max(a, dim=1)[0]

tensor([[5, 5, 7, 7],
        [0, 0, 9, 6],
        [8, 9, 8, 6],
        [2, 8, 2, 6],
        [4, 3, 3, 9],
        [4, 4, 9, 4]])
tensor([2, 0, 3, 2, 3, 2])


(tensor([[7],
         [0],
         [6],
         [2],
         [9],
         [9]]),
 tensor([7, 9, 9, 8, 9, 9]))