In [7]:
import torch
from torch.nn import functional as F

a = torch.randn((2, 4))
print(a)



print("dim=0 : \n", F.normalize(a, dim=0))
print("dim=1 : \n", F.normalize(a, dim=1))
# print("dim=2 : \n", F.normalize(a, dim=2))

tensor([[-0.6338,  0.7641, -0.5981,  0.8229],
        [ 0.4996,  0.1373, -0.3870, -0.5579]])
dim=0 : 
 tensor([[-0.7853,  0.9842, -0.8396,  0.8277],
        [ 0.6191,  0.1769, -0.5432, -0.5611]])
dim=1 : 
 tensor([[-0.4459,  0.5375, -0.4208,  0.5790],
        [ 0.5850,  0.1608, -0.4531, -0.6532]])


In [35]:
b = torch.randn(2, 5)
l2_norm_b = b[0].pow(2).sum(dim=0).sqrt()
print("b:", b)
# print(b[0].pow(2))
# print(b[0].pow(2).sum(dim=0))
print("b[0]'s l2 norm1:", b[0].pow(2).sum(dim=0).sqrt()) # l2 norm
print("b[0]'s l2 norm2:",b[0].norm(p=2))
print("b's l2 norm for dim=0:", b.norm(p=2, dim=0)) # dim=0는 열벡터를 대상으로 l2-norm을 계산한다
print("b's l2 norm for dim=1:", b.norm(p=2, dim=1)) # dim=1은 행벡터를 대상으로 l2-norm을 계산한다
print("result:", b[0] / l2_norm_b)
print(F.normalize(b, dim=0)) # dim=0는 열벡터를 대상으로 l2-norm을 구한 후, 그것으로 해당 열벡터를 나누어준다
print(F.normalize(b, dim=1)) # dim=0는 행벡터를 대상으로 l2-norm을 구한 후, 그것으로 해당 열벡터를 나누어준다

b: tensor([[ 1.0829, -0.0295, -1.7488,  0.4186,  0.7548],
        [ 0.6360,  1.0479, -0.5975, -0.1881, -1.9562]])
b[0]'s l2 norm1: tensor(2.2309)
b[0]'s l2 norm2: tensor(2.2309)
b's l2 norm for dim=0: tensor([1.2559, 1.0483, 1.8481, 0.4590, 2.0967])
b's l2 norm for dim=1: tensor([2.2309, 2.3920])
result: tensor([ 0.4854, -0.0132, -0.7839,  0.1877,  0.3383])
tensor([[ 0.8623, -0.0282, -0.9463,  0.9122,  0.3600],
        [ 0.5065,  0.9996, -0.3233, -0.4098, -0.9330]])


In [38]:
(b[0][0])**2 + (b[1][0])**2, ((b[0][0])**2 + (b[1][0])**2).sqrt()

(tensor(1.5772), tensor(1.2559))

In [43]:
temp = ((b[0][0])**2 + (b[1][0])**2).sqrt()
b[:,0], b[:,0] / temp, F.normalize(b, dim=1), b[0] / b[0].norm(p=2)

(tensor([1.0829, 0.6360]),
 tensor([0.8623, 0.5065]),
 tensor([[ 0.4854, -0.0132, -0.7839,  0.1877,  0.3383],
         [ 0.2659,  0.4381, -0.2498, -0.0786, -0.8178]]),
 tensor([ 0.4854, -0.0132, -0.7839,  0.1877,  0.3383]))

In [45]:
c = torch.randn(2, 5, 3)
print("c:", c)
print("c[0]'s l2-norm:", )
print("c's l2-norm for dim=1:", c.norm(p=2, dim=1))

c: tensor([[[ 2.4076,  0.6395, -1.0288],
         [ 0.8348, -0.0673,  0.2569],
         [-1.6670, -1.1554, -0.8397],
         [ 1.6511, -0.4965, -1.0464],
         [-1.5346,  0.0793, -1.6101]],

        [[ 0.5988, -1.2387, -0.3977],
         [ 1.0521,  0.8725, -1.8012],
         [ 2.0297, -0.7708,  0.0253],
         [-0.2835, -1.3225,  1.1519],
         [-0.2631, -0.6514, -1.0643]]])
c[0]'s l2-norm:
c's l2-norm for dim=1: tensor([[3.7886, 1.4147, 2.3488],
        [2.3947, 2.2501, 2.4213]])


In [51]:
c[0, :, 0], c[0, :, 0].pow(2), c[0, :, 0].pow(2).sum().sqrt()

(tensor([ 2.4076,  0.8348, -1.6670,  1.6511, -1.5346]),
 tensor([5.7967, 0.6969, 2.7789, 2.7262, 2.3551]),
 tensor(3.7886))

In [53]:
torch.randn(2, 3), torch.randn(2, 3).view(-1)

(tensor([[-2.1045, -1.7905,  1.4315],
         [-0.1176,  0.2865, -0.0240]]),
 tensor([ 0.4758,  1.4892,  2.4512, -1.5756, -0.6415,  1.8496]))