In [1]:
import torch

In [5]:
a = torch.randn(6)
b = torch.randn(6)
print(a, b)

torch.stack([a, b], dim=0), torch.stack([a, b], dim=1)

tensor([-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449]) tensor([ 0.6784,  0.5394,  1.0286, -0.9952, -1.1989, -0.6464])


(tensor([[-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449],
         [ 0.6784,  0.5394,  1.0286, -0.9952, -1.1989, -0.6464]]),
 tensor([[-0.3058,  0.6784],
         [-0.3893,  0.5394],
         [-0.1983,  1.0286],
         [-0.6638, -0.9952],
         [-2.1485, -1.1989],
         [-0.7449, -0.6464]]))

In [9]:
torch.cat([a, b], dim=0), torch.cat((a, b), dim=0)

(tensor([-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449,  0.6784,  0.5394,
          1.0286, -0.9952, -1.1989, -0.6464]),
 tensor([-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449,  0.6784,  0.5394,
          1.0286, -0.9952, -1.1989, -0.6464]))

In [11]:
a = 0
b = 0
b += (a = 1)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3782791330.py, line 3)

In [3]:
import os
import torch

print(os.getcwd())
# os.path.join(os.getcwd(), "path")

a = torch.randn(15)
print(a)
torch.save(a, os.path.join(os.getcwd(), "testing.pt"))

D:\for_study\workspace\for_reinf\tuorial
tensor([-0.3039, -1.2627,  0.0937, -0.3071, -0.8841,  0.3720,  0.0796, -0.6841,
        -0.6401,  0.3529,  0.4059, -1.4114,  0.4827,  0.5353,  0.8624])


In [4]:
torch.load(os.path.join(os.getcwd(), "testing.pt"), weights_only=True)

tensor([-0.3039, -1.2627,  0.0937, -0.3071, -0.8841,  0.3720,  0.0796, -0.6841,
        -0.6401,  0.3529,  0.4059, -1.4114,  0.4827,  0.5353,  0.8624])

In [5]:
b = [torch.randn(15) for i in range(10)]
print(b)
torch.save(b, os.path.join(os.getcwd(), "testing2.pt"))

[tensor([-2.0801, -0.8834, -0.1093,  0.4026, -0.8084, -0.5031, -0.7223,  0.5486,
        -1.8295, -1.2566,  0.7940,  0.0232, -0.5022,  0.9675,  0.8152]), tensor([ 1.1345, -0.1101, -0.8508,  1.4997, -1.4561,  1.6764,  0.8840,  1.3018,
        -0.7076,  1.9412,  1.6018,  0.9399,  0.9224, -0.4446,  0.7501]), tensor([-1.3372, -0.2349, -0.4875,  0.6193,  0.3065,  1.8824,  0.2980, -0.5509,
         0.4504,  0.3133, -0.3735, -1.5076, -0.5589,  1.4122, -0.6353]), tensor([ 0.7540,  0.2965, -0.1527, -2.1296, -0.5037,  0.6890, -2.4656,  1.6724,
        -0.3753, -0.4706, -2.2037,  0.3474,  0.4155, -1.0563, -0.3225]), tensor([-0.0653, -0.6230,  0.1559, -0.5800,  1.2302, -0.4643,  0.1135, -0.1638,
         0.0379, -0.1002,  0.6226,  0.4945,  0.2260, -0.4170,  1.3747]), tensor([-0.9733, -0.7468, -2.0663,  1.7850,  0.5187,  0.1300,  0.6729,  0.0582,
         1.7667,  0.8311,  1.2898, -1.2218,  0.8326,  1.2464, -0.3144]), tensor([ 1.7427, -0.5403,  0.0422,  0.8447, -0.8817,  0.6064, -1.5387,  0.4104,
 

In [6]:
c = torch.load(os.path.join(os.getcwd(), "testing2.pt"), weights_only=True)
print(c)

[tensor([-2.0801, -0.8834, -0.1093,  0.4026, -0.8084, -0.5031, -0.7223,  0.5486,
        -1.8295, -1.2566,  0.7940,  0.0232, -0.5022,  0.9675,  0.8152]), tensor([ 1.1345, -0.1101, -0.8508,  1.4997, -1.4561,  1.6764,  0.8840,  1.3018,
        -0.7076,  1.9412,  1.6018,  0.9399,  0.9224, -0.4446,  0.7501]), tensor([-1.3372, -0.2349, -0.4875,  0.6193,  0.3065,  1.8824,  0.2980, -0.5509,
         0.4504,  0.3133, -0.3735, -1.5076, -0.5589,  1.4122, -0.6353]), tensor([ 0.7540,  0.2965, -0.1527, -2.1296, -0.5037,  0.6890, -2.4656,  1.6724,
        -0.3753, -0.4706, -2.2037,  0.3474,  0.4155, -1.0563, -0.3225]), tensor([-0.0653, -0.6230,  0.1559, -0.5800,  1.2302, -0.4643,  0.1135, -0.1638,
         0.0379, -0.1002,  0.6226,  0.4945,  0.2260, -0.4170,  1.3747]), tensor([-0.9733, -0.7468, -2.0663,  1.7850,  0.5187,  0.1300,  0.6729,  0.0582,
         1.7667,  0.8311,  1.2898, -1.2218,  0.8326,  1.2464, -0.3144]), tensor([ 1.7427, -0.5403,  0.0422,  0.8447, -0.8817,  0.6064, -1.5387,  0.4104,
 

In [12]:
m1 = torch.nn.Softmax(dim=0)
m2 = torch.nn.Softmax(dim=1)
input = torch.randn(2, 3)
print(input)
output1 = m1(input)
print(output1)
output2 = m2(input)
print(output2)

tensor([[ 2.4516, -0.3414, -0.9459],
        [-0.9278,  0.4045, -0.3463]])
tensor([[0.9671, 0.3217, 0.3544],
        [0.0329, 0.6783, 0.6456]])
tensor([[0.9135, 0.0559, 0.0306],
        [0.1520, 0.5761, 0.2719]])


In [15]:
sum([0.9135, 0.0559, 0.0306]), sum([0.1229, 0.3017, 0.5754])

(1.0, 1.0)

In [14]:
input = torch.randn(1, 3)
print(input)
m1(input), m2(input)

tensor([[-1.0843, -0.1864,  0.4594]])


(tensor([[1., 1., 1.]]), tensor([[0.1229, 0.3017, 0.5754]]))