In [1]:
import torch
import numpy as np

In [5]:
a = torch.randn(6)
b = torch.randn(6)
print(a, b)

torch.stack([a, b], dim=0), torch.stack([a, b], dim=1)

tensor([-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449]) tensor([ 0.6784,  0.5394,  1.0286, -0.9952, -1.1989, -0.6464])


(tensor([[-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449],
         [ 0.6784,  0.5394,  1.0286, -0.9952, -1.1989, -0.6464]]),
 tensor([[-0.3058,  0.6784],
         [-0.3893,  0.5394],
         [-0.1983,  1.0286],
         [-0.6638, -0.9952],
         [-2.1485, -1.1989],
         [-0.7449, -0.6464]]))

In [9]:
torch.cat([a, b], dim=0), torch.cat((a, b), dim=0)

(tensor([-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449,  0.6784,  0.5394,
          1.0286, -0.9952, -1.1989, -0.6464]),
 tensor([-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449,  0.6784,  0.5394,
          1.0286, -0.9952, -1.1989, -0.6464]))

In [11]:
a = 0
b = 0
b += (a = 1)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3782791330.py, line 3)

In [3]:
import os
import torch

print(os.getcwd())
# os.path.join(os.getcwd(), "path")

a = torch.randn(15)
print(a)
torch.save(a, os.path.join(os.getcwd(), "testing.pt"))

D:\for_study\workspace\for_reinf\tuorial
tensor([-0.3039, -1.2627,  0.0937, -0.3071, -0.8841,  0.3720,  0.0796, -0.6841,
        -0.6401,  0.3529,  0.4059, -1.4114,  0.4827,  0.5353,  0.8624])


In [4]:
torch.load(os.path.join(os.getcwd(), "testing.pt"), weights_only=True)

tensor([-0.3039, -1.2627,  0.0937, -0.3071, -0.8841,  0.3720,  0.0796, -0.6841,
        -0.6401,  0.3529,  0.4059, -1.4114,  0.4827,  0.5353,  0.8624])

In [5]:
b = [torch.randn(15) for i in range(10)]
print(b)
torch.save(b, os.path.join(os.getcwd(), "testing2.pt"))

[tensor([-2.0801, -0.8834, -0.1093,  0.4026, -0.8084, -0.5031, -0.7223,  0.5486,
        -1.8295, -1.2566,  0.7940,  0.0232, -0.5022,  0.9675,  0.8152]), tensor([ 1.1345, -0.1101, -0.8508,  1.4997, -1.4561,  1.6764,  0.8840,  1.3018,
        -0.7076,  1.9412,  1.6018,  0.9399,  0.9224, -0.4446,  0.7501]), tensor([-1.3372, -0.2349, -0.4875,  0.6193,  0.3065,  1.8824,  0.2980, -0.5509,
         0.4504,  0.3133, -0.3735, -1.5076, -0.5589,  1.4122, -0.6353]), tensor([ 0.7540,  0.2965, -0.1527, -2.1296, -0.5037,  0.6890, -2.4656,  1.6724,
        -0.3753, -0.4706, -2.2037,  0.3474,  0.4155, -1.0563, -0.3225]), tensor([-0.0653, -0.6230,  0.1559, -0.5800,  1.2302, -0.4643,  0.1135, -0.1638,
         0.0379, -0.1002,  0.6226,  0.4945,  0.2260, -0.4170,  1.3747]), tensor([-0.9733, -0.7468, -2.0663,  1.7850,  0.5187,  0.1300,  0.6729,  0.0582,
         1.7667,  0.8311,  1.2898, -1.2218,  0.8326,  1.2464, -0.3144]), tensor([ 1.7427, -0.5403,  0.0422,  0.8447, -0.8817,  0.6064, -1.5387,  0.4104,
 

In [6]:
c = torch.load(os.path.join(os.getcwd(), "testing2.pt"), weights_only=True)
print(c)

[tensor([-2.0801, -0.8834, -0.1093,  0.4026, -0.8084, -0.5031, -0.7223,  0.5486,
        -1.8295, -1.2566,  0.7940,  0.0232, -0.5022,  0.9675,  0.8152]), tensor([ 1.1345, -0.1101, -0.8508,  1.4997, -1.4561,  1.6764,  0.8840,  1.3018,
        -0.7076,  1.9412,  1.6018,  0.9399,  0.9224, -0.4446,  0.7501]), tensor([-1.3372, -0.2349, -0.4875,  0.6193,  0.3065,  1.8824,  0.2980, -0.5509,
         0.4504,  0.3133, -0.3735, -1.5076, -0.5589,  1.4122, -0.6353]), tensor([ 0.7540,  0.2965, -0.1527, -2.1296, -0.5037,  0.6890, -2.4656,  1.6724,
        -0.3753, -0.4706, -2.2037,  0.3474,  0.4155, -1.0563, -0.3225]), tensor([-0.0653, -0.6230,  0.1559, -0.5800,  1.2302, -0.4643,  0.1135, -0.1638,
         0.0379, -0.1002,  0.6226,  0.4945,  0.2260, -0.4170,  1.3747]), tensor([-0.9733, -0.7468, -2.0663,  1.7850,  0.5187,  0.1300,  0.6729,  0.0582,
         1.7667,  0.8311,  1.2898, -1.2218,  0.8326,  1.2464, -0.3144]), tensor([ 1.7427, -0.5403,  0.0422,  0.8447, -0.8817,  0.6064, -1.5387,  0.4104,
 

In [12]:
m1 = torch.nn.Softmax(dim=0)
m2 = torch.nn.Softmax(dim=1)
input = torch.randn(2, 3)
print(input)
output1 = m1(input)
print(output1)
output2 = m2(input)
print(output2)

tensor([[ 2.4516, -0.3414, -0.9459],
        [-0.9278,  0.4045, -0.3463]])
tensor([[0.9671, 0.3217, 0.3544],
        [0.0329, 0.6783, 0.6456]])
tensor([[0.9135, 0.0559, 0.0306],
        [0.1520, 0.5761, 0.2719]])


In [15]:
sum([0.9135, 0.0559, 0.0306]), sum([0.1229, 0.3017, 0.5754])

(1.0, 1.0)

In [14]:
input = torch.randn(1, 3)
print(input)
m1(input), m2(input)

tensor([[-1.0843, -0.1864,  0.4594]])


(tensor([[1., 1., 1.]]), tensor([[0.1229, 0.3017, 0.5754]]))

In [4]:
import torch

a = torch.randn(10)
b = torch.randn(10)
print(a)
print(b)
a[0:5], a[5:], torch.cat((a[0:5], b[5:]), dim=0)

tensor([-1.0117,  0.7827, -2.2590,  1.4592,  0.1869,  0.6988,  0.5708,  0.0792,
        -0.1561,  0.6419])
tensor([-1.0025, -0.2602, -0.2354,  0.7131,  0.5041,  1.5426,  1.3286,  1.2665,
         0.7528, -0.2919])


(tensor([-1.0117,  0.7827, -2.2590,  1.4592,  0.1869]),
 tensor([ 0.6988,  0.5708,  0.0792, -0.1561,  0.6419]),
 tensor([-1.0117,  0.7827, -2.2590,  1.4592,  0.1869,  1.5426,  1.3286,  1.2665,
          0.7528, -0.2919]))

In [8]:
torch.zeros(10).dtype, torch.randn(10).dtype

(torch.float32, torch.float32)

In [2]:
a = torch.randn(10)
a, a[:-1]

(tensor([ 1.7675, -1.4327, -0.0604,  1.1978,  0.4926, -1.6226,  0.3035, -1.3382,
          2.0547, -1.2433]),
 tensor([ 1.7675, -1.4327, -0.0604,  1.1978,  0.4926, -1.6226,  0.3035, -1.3382,
          2.0547]))

In [19]:
t = torch.randn(4)
t.unsqueeze(dim=0), t.unsqueeze(dim=1), t.view(1, 4)

(tensor([[-1.1177,  0.9291, -0.7798,  0.6579]]),
 tensor([[-1.1177],
         [ 0.9291],
         [-0.7798],
         [ 0.6579]]),
 tensor([[-1.1177,  0.9291, -0.7798,  0.6579]]))

In [3]:
import numpy as np
import torch
from torch import nn

class LR_block(nn.Module):
    def __init__(self, shape):
        super().__init__()
        self.linear = nn.Linear(shape[0], shape[1])
        self.relu = nn.ReLU()

    def forward(self, x):
        output = self.relu(self.linear(x))

        return output

class Model(nn.Module):
    def __init__(self, layers):
        super().__init__()
        self.body = nn.Sequential(*[LR_block(shape) for shape in layers[:-1]])
        self.tail_top = nn.Linear(layers[-1][0], layers[-1][1])
        self.tail_bottom = nn.LogSoftmax(dim=0)

    def forward(self, x):
        output = self.body(x)
        output = self.tail_top(output)
        print("tail_top :", output, output.size())
        output = self.tail_bottom(output)

        return output

model = Model(layers=[(4, 25), (25, 10), (10, 2)])

# model.eval()
inputs = torch.randn(4)
print(inputs, inputs.size())
model(inputs)
# model(torch.randn(4))

tensor([-0.5492,  0.6293,  1.3954,  0.1263]) torch.Size([4])
tail_top : tensor([ 0.0366, -0.0669], grad_fn=<ViewBackward0>) torch.Size([2])


tensor([-0.6428, -0.7462], grad_fn=<LogSoftmaxBackward0>)

In [44]:
for x in model.state_dict():
    print(x, type(x))

body.0.linear.weight <class 'str'>
body.0.linear.bias <class 'str'>
body.1.linear.weight <class 'str'>
body.1.linear.bias <class 'str'>
tail_top.weight <class 'str'>
tail_top.bias <class 'str'>


In [39]:
model.state_dict()

OrderedDict([('body.0.linear.weight',
              tensor([[-1.0373,  1.0263, -1.1266,  0.4110],
                      [ 0.6123, -1.5306,  0.1576, -0.5357],
                      [-0.5707,  1.6880, -1.4288, -0.4595],
                      [-0.3543,  1.4065, -2.2359, -0.3465],
                      [ 1.2357, -0.6525,  0.4971,  0.1741],
                      [ 0.9517, -0.5386,  1.6081,  0.4391],
                      [ 0.6090,  0.4993, -0.4316, -2.0231],
                      [ 0.9479,  0.2763, -0.2485, -1.0919],
                      [ 0.6749, -0.5598,  0.8473, -3.5738],
                      [-0.1479,  0.2433, -1.7256, -0.0615],
                      [-1.6479, -1.3993, -1.6240,  0.2031],
                      [-0.5054, -1.2080,  0.0083, -1.7554],
                      [ 2.7853,  0.4304, -1.0680,  1.6424],
                      [-1.3214,  1.0011,  0.8417,  0.8181],
                      [ 1.2319,  1.4374,  0.8976,  1.2449],
                      [-1.1747,  0.0709,  0.9324, -0.6247],
  

In [33]:
model.state_dict()["body.0.linear.weight"], model.state_dict()["body.0.linear.weight"].size()

(tensor([[-1.0373,  1.0263, -1.1266,  0.4110],
         [ 0.6123, -1.5306,  0.1576, -0.5357],
         [-0.5707,  1.6880, -1.4288, -0.4595],
         [-0.3543,  1.4065, -2.2359, -0.3465],
         [ 1.2357, -0.6525,  0.4971,  0.1741],
         [ 0.9517, -0.5386,  1.6081,  0.4391],
         [ 0.6090,  0.4993, -0.4316, -2.0231],
         [ 0.9479,  0.2763, -0.2485, -1.0919],
         [ 0.6749, -0.5598,  0.8473, -3.5738],
         [-0.1479,  0.2433, -1.7256, -0.0615],
         [-1.6479, -1.3993, -1.6240,  0.2031],
         [-0.5054, -1.2080,  0.0083, -1.7554],
         [ 2.7853,  0.4304, -1.0680,  1.6424],
         [-1.3214,  1.0011,  0.8417,  0.8181],
         [ 1.2319,  1.4374,  0.8976,  1.2449],
         [-1.1747,  0.0709,  0.9324, -0.6247],
         [-2.3283,  0.5170, -0.8436, -0.0109],
         [ 0.2837,  0.1386,  0.1360,  0.1534],
         [ 0.3094,  0.5085,  0.4227,  0.7316],
         [ 2.1544,  0.4714, -0.1137,  0.0906],
         [ 0.4546,  1.0216,  0.6579, -0.0618],
         [ 1.

In [32]:
model.state_dict()["body.0.linear.weight"].copy_(torch.randn(25, 4))

tensor([[-1.0373,  1.0263, -1.1266,  0.4110],
        [ 0.6123, -1.5306,  0.1576, -0.5357],
        [-0.5707,  1.6880, -1.4288, -0.4595],
        [-0.3543,  1.4065, -2.2359, -0.3465],
        [ 1.2357, -0.6525,  0.4971,  0.1741],
        [ 0.9517, -0.5386,  1.6081,  0.4391],
        [ 0.6090,  0.4993, -0.4316, -2.0231],
        [ 0.9479,  0.2763, -0.2485, -1.0919],
        [ 0.6749, -0.5598,  0.8473, -3.5738],
        [-0.1479,  0.2433, -1.7256, -0.0615],
        [-1.6479, -1.3993, -1.6240,  0.2031],
        [-0.5054, -1.2080,  0.0083, -1.7554],
        [ 2.7853,  0.4304, -1.0680,  1.6424],
        [-1.3214,  1.0011,  0.8417,  0.8181],
        [ 1.2319,  1.4374,  0.8976,  1.2449],
        [-1.1747,  0.0709,  0.9324, -0.6247],
        [-2.3283,  0.5170, -0.8436, -0.0109],
        [ 0.2837,  0.1386,  0.1360,  0.1534],
        [ 0.3094,  0.5085,  0.4227,  0.7316],
        [ 2.1544,  0.4714, -0.1137,  0.0906],
        [ 0.4546,  1.0216,  0.6579, -0.0618],
        [ 1.1613, -1.1940,  0.7987

In [46]:
sd = model.state_dict()
model.state_dict().copy_(sd)
model.load_state_dict(

AttributeError: 'collections.OrderedDict' object has no attribute 'copy_'

In [29]:
tensor1 = torch.randn(2, 3)
tensor2 = tensor1.t()
print(tensor1)
print(tensor2)

tensor1[0][0] = 0.0
print(tensor1)
print(tensor2)

tensor([[ 0.3031,  0.0719,  0.3932],
        [-0.8953, -0.7288, -0.7219]])
tensor([[ 0.3031, -0.8953],
        [ 0.0719, -0.7288],
        [ 0.3932, -0.7219]])
tensor([[ 0.0000,  0.0719,  0.3932],
        [-0.8953, -0.7288, -0.7219]])
tensor([[ 0.0000, -0.8953],
        [ 0.0719, -0.7288],
        [ 0.3932, -0.7219]])


In [5]:
import numpy as np

a = np.array([[1, 2],
         [2, 10],
         [3, 6],
         [4, 4]])

a[:, 1], a[a[:, 1].argsort()], np.prod((21, 5))

(array([ 2, 10,  6,  4]),
 array([[ 1,  2],
        [ 4,  4],
        [ 3,  6],
        [ 2, 10]]),
 105)

In [6]:
for l in enumerate([(21, 5), (57, 68)]):
    print(l)

(0, (21, 5))
(1, (57, 68))


In [9]:
lp = 500
p_num = 8
print(lp / p_num)
print(lp // p_num)
temp = np.arange(0, 500, lp // p_num)
print(temp)
temp[-1] = lp
print(temp)
for i in range(temp[1], temp[2]):
    print(i)

62.5
62
[  0  62 124 186 248 310 372 434 496]
[  0  62 124 186 248 310 372 434 500]
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123


In [20]:
a = torch.randn(10, 10)
b = torch.randn(10)
print(a, b)
# a[0] = b
print(a[0, 0])

tensor([[ 1.2034, -0.5259,  0.5125,  1.1562,  0.2999, -1.4160, -0.1917, -1.6225,
          0.3840,  0.5920],
        [ 0.1097, -1.5858, -0.5263, -1.4627, -1.1548, -1.6947, -0.4991,  0.1238,
          0.6323, -0.8867],
        [ 0.1337,  1.3467, -0.7563,  0.2350,  0.8541, -0.3491, -0.1676, -1.9574,
          0.5570,  0.8421],
        [-0.1643, -0.4155, -1.3321, -0.4866, -1.6714,  0.4927, -0.6049,  0.1574,
         -0.0553, -0.4910],
        [-0.1835,  0.2477, -0.0653,  0.4680, -0.5385, -1.7241,  1.1194, -0.9305,
         -0.8875,  0.1095],
        [-0.6208,  1.3446,  0.7856,  1.4177,  2.8440,  0.5824, -1.2749, -2.1885,
         -0.2381, -1.0418],
        [-1.0280, -0.1011,  1.1200,  1.8254,  1.7841,  0.5287, -0.4050,  1.2639,
         -1.4922, -0.1206],
        [ 0.8365,  1.7667,  1.7844,  0.7974, -0.1370,  1.5669,  0.0465, -1.0722,
         -0.5338, -0.1851],
        [ 1.4040,  0.5069, -0.0738,  1.7375, -0.4734, -1.2608,  0.9836, -2.2751,
          1.6068,  0.0938],
        [ 0.9145,  

In [24]:
a = torch.tensor([1,2,3,4,5,6], dtype=torch.float32)
a.mean()

tensor(3.5000)

In [46]:
lts = 250
p_num = 8
temp = np.arange(0, lts+1, lts // p_num)
temp[-1] = lts
temp, temp[7:9], temp[*[7, 8]]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed