In [1]:
import torch

In [5]:
a = torch.randn(6)
b = torch.randn(6)
print(a, b)

torch.stack([a, b], dim=0), torch.stack([a, b], dim=1)

tensor([-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449]) tensor([ 0.6784,  0.5394,  1.0286, -0.9952, -1.1989, -0.6464])


(tensor([[-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449],
         [ 0.6784,  0.5394,  1.0286, -0.9952, -1.1989, -0.6464]]),
 tensor([[-0.3058,  0.6784],
         [-0.3893,  0.5394],
         [-0.1983,  1.0286],
         [-0.6638, -0.9952],
         [-2.1485, -1.1989],
         [-0.7449, -0.6464]]))

In [9]:
torch.cat([a, b], dim=0), torch.cat((a, b), dim=0)

(tensor([-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449,  0.6784,  0.5394,
          1.0286, -0.9952, -1.1989, -0.6464]),
 tensor([-0.3058, -0.3893, -0.1983, -0.6638, -2.1485, -0.7449,  0.6784,  0.5394,
          1.0286, -0.9952, -1.1989, -0.6464]))

In [11]:
a = 0
b = 0
b += (a = 1)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3782791330.py, line 3)