In [6]:
import torch
from torch import nn

a = torch.tensor([[1, 2]], dtype=torch.float)
m = nn.Softmax(dim=0)
m(a), m(a).sum(dim=0)

(tensor([[1., 1.]]), tensor([1., 1.]))

In [2]:
import torch

p = torch.tensor([[0.2, 0.3, 0.1, 0.4]])

[torch.multinomial(p, 1) for _ in range(10)]

[tensor([[3]]),
 tensor([[0]]),
 tensor([[0]]),
 tensor([[3]]),
 tensor([[3]]),
 tensor([[0]]),
 tensor([[3]]),
 tensor([[3]]),
 tensor([[1]]),
 tensor([[0]])]

In [8]:
import numpy as np

p = np.array([0.2, 0.3, 0.1, 0.4])
np.random.choice(np.array([0, 1, 2, 3]), p=p)

1

In [10]:
np.array([1,2,3,4,5,6,7,8,9,10]).shape[0]

10